''' Having 공부 좀 해 봐,,,
SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE A INNER JOIN REST_REVIEW  B 
ON A.MEMBER_ID=B.MEMBER_ID
WHERE B.MEMBER_ID IN (
    SELECT MEMBER_ID FROM REST_REVIEW
    GROUP BY MEMBER_ID HAVING COUNT(MEMBER_ID)=(SELECT MAX(COUNT(MEMBER_ID)) FROM REST_REVIEW GROUP BY MEMBER_ID))
ORDER BY REVIEW_DATE, REVIEW_TEXT
'''
SELECT PRO.MEMBER_NAME, REV.REVIEW_TEXT, DATE_FORMAT(REV.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE FROM MEMBER_PROFILE PRO
JOIN REST_REVIEW REV 
ON REV.MEMBER_ID = PRO.MEMBER_ID
WHERE PRO.MEMBER_NAME = (SELECT PROF.MEMBER_NAME FROM MEMBER_PROFILE PROF
                         JOIN REST_REVIEW REST
                         ON REST.MEMBER_ID = PROF.MEMBER_ID
                         GROUP BY MEMBER_NAME
                         ORDER BY COUNT(MEMBER_NAME) DESC
                         LIMIT 1)
ORDER BY REV.REVIEW_DATE, REV.REVIEW_TEXT
