SELECT TO_CHAR(S.SALES_DATE, 'YYYY') YEAR
     , TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM')) MONTH
     , COUNT(DISTINCT S.USER_ID) PUCHASED_USERS
     , ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*)
                                            FROM USER_INFO
                                           WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) PUCHASED_RATIO
  FROM USER_INFO I, ONLINE_SALE S
 WHERE I.USER_ID = S.USER_ID
   AND TO_CHAR(I.JOINED, 'YYYY') = '2021'
 GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM'))
 ORDER BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM'))