-- 코드를 입력하세요
SELECT CATEGORY,PRICE MAX_PRICE,PRODUCT_NAME FROM FOOD_PRODUCT
WHERE CATEGORY IN ( '과자', '국', '김치', '식용유')
AND PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;

--- 그냥 max(price) 출력 왜 틀린 것일까